### ISSUE TITLE
'Beam in Production'?

### ISSUE THREAD

**Issue by brucearctor** [beamsummit/beam-intro-berlin-2019#4]
What else do we want for this?  

I think we need Flink Cluster, maybe Spark clusters setup.  So a pointer to the IPs for those, eventually.  

Any other materials for intro talk?  Or just docs to be shared in repo?

**Comment by brucearctor** [comment]
Among other things, mobile gaming probably good example for submitting production jobs.  Mobile gaming too big/network intensive for local runner.  So, that gives something concrete, for now.  Bigger picture can come up with more/additional examples.

**Comment by pabloem** [comment]
I was not able to reliably do  Flink job submission to a cluster on GCP, so we'll just have to do it locally. I did not end up working on spark : /
